// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HealthcareAppointment.Models.Models
{
    public partial class User
    {
        public User()
        {
            AppointmentDoctors = new HashSet<Appointment>();
            AppointmentPatients = new HashSet<Appointment>();
        }

        public string Id { get; set; }
        [Required, MinLength(3), MaxLength(255)]
        public string Name { get; set; }
        [Required, EmailAddress, MinLength(5), MaxLength(255)]
        public string Email { get; set; }

        public DateTime? DateOfBirth { get; set; }
        [Required, MinLength(8)]
        public string Password { get; set; }
        public int Role { get; set; }
        public string Specialization { get; set; }

        public virtual ICollection<Appointment> AppointmentDoctors { get; set; }
        public virtual ICollection<Appointment> AppointmentPatients { get; set; }
    }
}